[package]
name = "s3insqlite"
version = "0.1.0"
edition = "2024"

[dependencies]
log = "0.4"
env_logger = "0.10"
chrono = "0.4"
actix-web = "4"
rusqlite = { version = "0.35", features = ["bundled"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
config = "0.13"
toml = "0.8"
r2d2 = "0.8"
r2d2_sqlite = "0.28"
url = "2.5.4"
