[package]
name = "s3insqlite"
version = "0.1.0"
edition = "2024"

[dependencies]
log = "0.4"
env_logger = "0.11"
chrono = "0.4"
actix-web = "4"
rusqlite = { version = "0.36", features = ["bundled"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
config = "0.15"
toml = "0.8"
r2d2 = "0.8"
r2d2_sqlite = "0.30"
url = "2"

[dev-dependencies]
ndarray = { version = "0.16" }
rand = { version = "0.9" }
opendal = { version = "0.53", features = ["services-s3"] }
zarrs = { version = "0.20", features = ["zstd", "async"] }
zarrs_opendal = { version = "0.7" }
