bind_address = "127.0.0.1"
port = 8080
database_path = "database.sqlite"
buckets = ["test"]
max_workers = 4
max_object_size = 104857600       # 100 MB, adjust as needed, default to 1 MB
log_path = "log.txt"
log_level = "info"
